config/routes.rb
Rails.application.routes.draw do
  resources :packages, only:[:index]
  resources :trackings, only:[:index, :load_labels_file] do
    collection do
      post  'load_labels_file', to: 'trackings#load_labels_file'
    end
  end

  root to: 'trackings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/package.rb
class Package < ApplicationRecord

  include UnitConverterModule

  validates :length, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :weight, presence: true
  validates :distance_unit, presence: true
  validates :mass_unit, presence: true

  has_one :label_tracking, :class_name => 'Tracking', foreign_key: 'label_package_id'
  has_one :real_tracking, :class_name => 'Tracking', foreign_key: 'real_package_id'

  def get_real_weight
    converter = UnitConverter.new(KilogramConverter.new(), self.mass_unit.downcase)
    converter.converter_unit_to_universal(self.weight)
  end

  def get_total_weight
    volumetric_weight = self.get_volumetric_weight
    converter = UnitConverter.new(KilogramConverter.new(), self.mass_unit.downcase)
    weight = converter.converter_unit_to_universal(self.weight)
    volumetric_weight > weight ? volumetric_weight : weight
  end

  def get_volumetric_weight
    converter = UnitConverter.new(CentimeterConverter.new(), self.distance_unit.downcase)
    (converter.converter_unit_to_universal(self.width) * converter.converter_unit_to_universal(self.height) * converter.converter_unit_to_universal(self.length)) / 5000
  end

  def get_weight_selected
    self.get_total_weight == self.weight ? '' : '(Volumetrico)'
  end

end

app/models/tracking.rb
class Tracking < ApplicationRecord

  belongs_to :label_package, class_name: "Package"
  belongs_to :real_package, class_name: "Package"

  validates :tracking_number, presence: true, uniqueness: true
  validates :carrier, presence: true
  validates :label_package, presence: true
  validates :real_package, presence: true

  def get_overweight
    overweight = self.real_package.get_total_weight - self.label_package.get_total_weight.ceil
    overweight > 0 ? overweight : 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController

  include Adapter

  def index
    respond_to do |format|
      format.html{ @tracking = Tracking.new }
      format.json {render json: TrackingsDatatable.new(view_context)}
    end
  end

  def load_labels_file

    if params[:upload][:file].present?
      carrier = nil
      file = File.read(params[:upload][:file].original_filename)
      data_labels = JSON.parse(file)

      data_labels.each do |label_data|

        if carrier.nil? && label_data['carrier'] == 'FEDEX'
          carrier = FedexAdapter.new
        end

        unless carrier.nil?
          tracking = Tracking.new(tracking_number: label_data['tracking_number'], carrier: label_data['carrier'])
          tracking.label_package = Package.new(length: label_data['parcel']['length'],
                                               width: label_data['parcel']['width'],
                                               height: label_data['parcel']['height'],
                                               weight: label_data['parcel']['weight'],
                                               distance_unit: label_data['parcel']['distance_unit'],
                                               mass_unit: label_data['parcel']['mass_unit'])

          tracking.real_package = Package.new(carrier.get_data_package(label_data['tracking_number']))

          tracking.save
        end

      end
    end

    respond_to do |format|
        format.html { redirect_to trackings_path, notice: I18n.t('messages.created') }
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def decorate(model, decorate_class = nil)
    (decorate_class || "#{model.class}Decorator".constantize).new(model)
  end
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('title_system') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', params[:controller], media: 'all' %>
    <%= javascript_include_tag 'application', params[:controller] %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trackings/_form.html.erb
<%= form_for(tracking,:url => load_labels_file_trackings_path,:html => { :multipart => true }) do |f| %>
  <% if tracking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracking.errors.count, "error") %> prohibited this tracking from being saved:</h2>
      <ul>
      <% tracking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-12">
      <label>Seleccione el archivo con las etiquetas de los paquetes (JSON).</label>
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-8 col-xs-12">
          <%= file_field_tag 'upload[file]', accept: 'application/json' %>
        </div>
        <div class="col-md-4 col-xs-12">
          <%= f.submit t("btn.load")%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/trackings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1><%= t('activerecord.models.trackings') %></h1>
    </div>

    <div class="col-12 title">
      <p id="notice"><%= notice %></p>
      <%= render 'form', tracking: @tracking %>
    </div>

    <div class="col-12 border-top my-3">
      <div class="card">
        <div class="card-body card-padding">

          <h2><%= t('activerecord.models.packages') %></h2>
          <div class="datatable_custom bootgrid-header">
            <table id="tracking-datatable" class="table table-responsive table-condensed table-custom" data-source="<%= trackings_url(format: "json")%>">
              <thead>
                <tr>
                  <th><%= t('activerecord.attributes.tracking.tracking_number') %></th>
                  <th><%= t('activerecord.attributes.tracking.carrier') %></th>
                  <th><%= t('ui.package.label_weight') %></th>
                  <th><%= t('ui.package.real_weight') %></th>
                  <th><%= t('ui.package.real_total_weight') %></th>
                  <th><%= t('ui.package.overweight') %></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>